# Generated by Django 5.2.1 on 2025-05-22 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demographics_name', models.CharField(max_length=100)),
                ('demographics_surname', models.CharField(max_length=100)),
                ('demographics_age', models.IntegerField()),
                ('demographics_address', models.TextField()),
                ('demographics_image', models.ImageField(upload_to='uploads/')),
                ('demographics_view_count', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
